food_delivery:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER', 'dbt_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dbt_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'food_delivery_dw') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
